dist: bionic
language: ruby
rvm:
  - 2.7.0

addons:
  apt:
    packages:
      - python3-pip
      - python3-venv

script: ./.ci/travis.sh

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - gem install bundler

cache:
  directories:
    - venv
    - vendor
