url: "https://lars.hupel.info"
logo: "/img/profile.jpg"
title: "Lars Hupel's website"
author:
  name: "Lars Hupel"
  twitter: "larsr_h"
  uri: "https://lars.hupel.info"
  picture: "/img/profile.jpg"
twitter:
  username: "larsr_h"
social:
  links:
    - "https://github.com/larsrh"
    - "https://twitter.com/larsr_h"
    - "https://instagram.com/larsr_h"
    - "https://keybase.io/larsrh"
    - "https://stackoverflow.com/users/4776939/larsrh"
include:
  - "_redirects"
exclude:
  - "img_assets"
  - "scripts"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - ".ruby-version"
  - ".ci"
  - "venv"
encoding: "utf-8"

collections:
  articles:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
      nav: articles
      card_theme: bg-dark text-white
      is_article: true
      description: ""
  - scope:
      path: ""
      type: research
    values:
      layout: research
      nav: academic
      card_theme: bg-success text-white
      is_research: true
      description: ""
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      nav: activities
      is_talk: true
      description: ""
