- text: Scala Symposium
  role: Programme Committee
  link: "http://conf.researchr.org/committee/scala-2016/scala2016-pc"
  date: 2016
- text: Typelevel Summit Philadelphia
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2016-03-summit-philadelphia/"
  date: 2016
- text: Typelevel Summit Oslo
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2016-05-summit-oslo/"
  date: 2016
- text: Computer Aided Verification
  role: Artifact Evaluation Committee
  link: "http://cavconference.org/2017/organization/"
  date: 2017
- text: Scala Symposium
  role: Programme Committee
  link: "http://conf.researchr.org/committee/scala-2017/scala-2017-papers-program-committee"
  date: 2017
- text: Typelevel Summit New York City
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2017-03-summit-nyc/"
  date: 2017
- text: Typelevel Summit Copenhagen
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2017-06-summit-copenhagen/"
  date: 2017
- text: Typelevel Summit Boston
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2018-03-summit-boston/"
  date: 2018
- text: Typelevel Summit Berlin
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2018-05-summit-berlin/"
  date: 2018
- text: Scala Days
  role: "Programme Committee"
  link: "https://eu.scaladays.org/"
  date: 2018
- text: Scala Center
  role: Community Representative at the Scala Center Advisory Board
  link: "https://scala.epfl.ch/"
  date: 2016–2018
- text: Scala Platform Process
  role: Committee
  link: "https://scalacenter.github.io/platform/"
  date: 2017–2018
- text: Scala Days
  role: "Programme Committee"
  link: "https://www.scaladays.org/"
  date: 2019
- text: Typelevel Summit Philadelphia
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2019-04-summit-philadelphia/"
  date: 2019
- text: Typelevel Summit Lausanne
  role: "Programme Committee, Organisation"
  link: "https://typelevel.org/event/2019-06-summit-lausanne/"
  date: 2019
- text: OOP
  role: "Reviewer"
  link: "https://www.oop-konferenz.de/oop2020.html"
  date: 2020
